<?php
$produkList = [
    [
        "id" => 1,
        "nama" => "Indonesian Waterose Face Mist",
        "harga" => "Rp35.000,00",
        "gambar" => "indonesian-waterose-face-mist.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Oily, Acne Prone Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "60ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Waterose Face Mist merupakan produk perawatan kulit yang terbuat dari sari bunga mawar asli, menghadirkan keindahan dan kekayaan alam Indonesia dalam setiap semprotannya. Dengan kandungan alami dari mawar, face mist ini memberikan sensasi ketenangan dan kesegaran bagi kulit, sekaligus membantu menjaga kesehatan dan kelembapan kulit secara alami. Produk ini memiliki berbagai manfaat, seperti menghidrasi kulit, meredakan radang atau iritasi, serta mengandung antibakteri yang mampu membersihkan kuman penyebab jerawat. Dengan penggunaan rutin, kulit akan tampak lebih segar, sehat, dan bercahaya.
    Penggunaan Waterose Face Mist sangat praktis, cukup dengan menutup mata dan menyemprotkannya secukupnya pada wajah untuk sensasi menyegarkan. Selain wajah, produk ini juga dapat diaplikasikan pada seluruh bagian tubuh, termasuk rambut, untuk memberikan kelembapan alami. Waterose Face Mist juga memiliki aroma lembut yang menenangkan, menjadikannya pilihan sempurna untuk relaksasi dan perawatan kulit."
    ],
    [
        "id" => 2,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 3,
        "nama" => "Waterymelon Deep Hydration Unscented Toner",
        "harga" => "Rp82.000,00",
        "gambar" => "waterymelon-deep-hydration-unscented-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "100ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang bekerja efektif untuk menghidrasi serta menenangkan kulit. Dengan tekstur ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit, memperkuat skin barrier, serta mengurangi kemerahan atau peradangan pada kulit wajah. Kandungan Watermelon memberikan hidrasi optimal, Aloe Vera Juice menenangkan dan meregenerasi kulit, sementara Niacinamide membantu mencerahkan kulit dan memudarkan bekas jerawat. Selain itu, Centella Asiatica berperan sebagai antioksidan yang meredakan kemerahan pada kulit berjerawat, sedangkan Sodium Hyaluronate menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini bebas dari fragrance, alkohol, paraben, dan minyak, sehingga aman bagi kulit yang rentan fungal acne. Hadir dalam ukuran 100 ml, toner ini dapat digunakan setiap pagi dan malam hari setelah mencuci wajah. Hydrating toner ini membantu kulit tetap sehat, dan segar seharian.",
    ],
    [
        "id" => 4,
        "nama" => "Oatmilk Gentle Facial Wash",
        "harga" => "Rp78.000,00",
        "gambar" => "oatmilk-gentle-facial-wash.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Sensitif, Dry, Combination, Iritated Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "100ml",
        "tekstur" => "Gel",
        "umur_simpan" => "6 Bulan",
        "deskripsi" => "Sabun cuci muka ini diformulasikan dengan oat dan susu asli untuk membersihkan wajah dari debu dan kotoran tanpa menghilangkan kelembapan alami kulit. Dengan tekstur yang lembut, produk ini tidak menyebabkan kulit terasa 'ketarik' setelah dibilas, sehingga aman untuk kulit sensitif. Selain membersihkan, butiran oat di dalamnya membantu mengangkat sel kulit mati dengan lembut, sementara kandungan sodium lactate dari susu menjaga keseimbangan pH dan kelembapan kulit. Rice bran serta glycerin berperan sebagai humektan untuk meningkatkan hidrasi dan menyegarkan permukaan kulit, sementara sodium hyaluronate sebagai Natural Moisturizing Factor membantu melindungi skin barrier agar tetap sehat. Sabun ini diformulasikan tanpa kandungan SLS, alkohol, dan paraben, sehingga lebih aman dan nyaman digunakan sehari-hari. Dengan kombinasi bahan-bahan berkualitas yang melembapkan serta melindungi kulit, sabun ini menjadi pilihan tepat untuk menjaga kesehatan kulit wajah tanpa khawatir iritasi atau kekeringan. Sabun ini juga memberikan efek menenangkan, menjadikan kulit terasa lebih halus, segar, dan nyaman setelah setiap pemakaian."
    ],
    [
        "id" => 5,
        "nama" => "Chill Out Calming Serum",
        "harga" => "Rp80.000,00",
        "gambar" => "chill-out-calming-serum.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Normal, Oily, Dry, Combination, Sensitive",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "30ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 bulan",
        "deskripsi" => "Chill Oat Calming Serum adalah serum yang diformulasikan khusus untuk menenangkan dan merawat kulit yang mengalami iritasi serta kemerahan. Diperkaya dengan Oat Extract (Avenaplex 1%), Niacinamide, Turmeric Extract, Ceramide, dan Allantoin, serum ini membantu memperkuat skin barrier, menjaga kelembapan, serta meningkatkan elastisitas kulit. Avenaplex 1% terbukti dapat meningkatkan kadar hyaluronic acid dan ceramide pada wajah hingga 14% dan 10%, sehingga kulit tetap terhidrasi dan sehat. Kandungan Pyrus Malus (Apple) Fruit Extract serta Phragmites Karka Extract & Poria Cocos Extract memberikan efek menyejukkan dan merawat kelembapan kulit wajah, sementara Curcuma Longa (rhizome) Extract bertindak sebagai antioksidan yang melindungi kulit dari radikal bebas.
    Serum ini cocok untuk semua jenis kulit, termasuk kulit sensitif dan berjerawat, karena bebas dari alkohol, paraben, dan pewangi. Dengan kombinasi bahan aktif yang menenangkan dan memperbaiki skin barrier, Chill Oat Calming Serum membantu kulit terasa lebih lembap, kenyal, dan terlindungi dari iritasi. Serum ini juga cepat meresap tanpa rasa lengket."
    ],
    [
        "id" => 6,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 7,
        "nama" => "Oatmilk Day Creme",
        "harga" => "Rp70.000,00",
        "gambar" => "oatmilk-day-cream.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Sensitive, Acne Prone, Combination, Dry",
        "waktu_penggunaan" => "Pagi hari",
        "berat_bersih" => "25ml",
        "tekstur" => "Krim",
        "umur_simpan" => "6 bulan",
        "deskripsi" => "Harlette Oatmilk Day Crème adalah pelembap wajah yang diformulasikan dengan oat, susu, dan niacinamide untuk memberikan hidrasi optimal serta perlindungan dari paparan sinar matahari. Dengan tekstur ringan yang mudah meresap, pelembap ini membantu mengontrol produksi sebum, menjaga keseimbangan pH kulit, serta memberikan tampilan fresh glow finish tanpa meninggalkan whitecast. Kandungan hero ingredients seperti Oat yang menenangkan kulit sensitif, Sodium Lactate dari susu yang menjaga kelembapan, serta Niacinamide yang memperkuat skin barrier dan mencerahkan kulit, menjadikan produk ini cocok untuk semua jenis kulit, termasuk kulit sensitif. Rice Bran juga turut berperan dalam melembapkan dan melindungi kulit agar tetap halus dan sehat.
    Untuk mendapatkan manfaat maksimal, Oatmilk Day Crème diaplikasikan sebagai langkah terakhir dalam rutinitas skincare pada pagi hari dengan cara mengoleskan secukupnya ke seluruh wajah. Dengan perlindungan dari sinar UV dan efek melembapkannya, pelembap ini membantu kulit tetap sehat dan segar sepanjang hari. Pelembap ini juga memberikan rasa nyaman tanpa lengket."
    ],
    [
        "id" => 8,
        "nama" => "Oat Probiotic Lightweight Sunscreen SPF 50",
        "harga" => "Rp90.000,00",
        "gambar" => "oat-probiotic-lightweight.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Normal, Oily, Dry, Combination, Sensitive, Acne Prone",
        "waktu_penggunaan" => "Pagi hari",
        "berat_bersih" => "40ml",
        "tekstur" => "Krim",
        "umur_simpan" => "12 bulan",
        "deskripsi" => "Tabir surya ini memiliki tekstur ringan, mudah meresap, dan cocok untuk semua jenis kulit, termasuk kulit sensitif dan berjerawat. Dengan SPF 50 dan PA++++, produk ini memberikan perlindungan optimal dari sinar UVA dan UVB tanpa meninggalkan whitecast, sehingga wajah tetap tampak natural dan segar. Selain perlindungan dari sinar matahari, sunscreen ini juga mengandung bahan aktif yang mampu melindungi kulit dari dampak buruk polusi dan blue light yang dihasilkan dari gadget. Ditambah dengan finish yang ringan dan matte, sunscreen ini nyaman dipakai sehari-hari, bahkan cocok digunakan di bawah makeup tanpa membuat riasan luntur atau terasa berminyak. Dengan kombinasi perlindungan maksimal, kelembapan tahan lama, dan bahan-bahan yang menutrisi kulit, Oat Probiotic Lightweight Sunscreen SPF 50 adalah pilihan sempurna untuk menjaga kulit tetap sehat, segar, dan terlindungi sepanjang hari — baik saat beraktivitas di luar ruangan maupun di dalam ruangan. Sunscreen ini juga diformulasikan tanpa alkohol, paraben, dan pewangi, sehingga aman untuk kulit sensitif.",
    ],
    [
        "id" => 9,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 10,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 11,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 12,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 13,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 14,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 15,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 16,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 17,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 18,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 19,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
    [
        "id" => 20,
        "nama" => "Waterymelon Deep Hydration Toner",
        "harga" => "Rp145.000,00",
        "gambar" => "waterymelon-deep-hydration-toner.jpeg",
        "merek" => "Harlette",
        "kondisi_kulit" => "Dry, Dehydrated, Combination, Sensitive Skin",
        "waktu_penggunaan" => "Pagi hari dan Malam hari",
        "berat_bersih" => "200ml",
        "tekstur" => "Cair",
        "umur_simpan" => "12 Bulan",
        "deskripsi" => "Hydrating toner ini diformulasikan dengan kombinasi bahan aktif seperti Watermelon, Sodium Hyaluronate, Centella Asiatica, dan Niacinamide, yang efektif memberikan lapisan hidrasi sekaligus menenangkan kulit. Dengan tekstur yang ringan dan mudah menyerap, toner ini membantu menjaga keseimbangan pH kulit serta memperkuat skin barrier, sehingga kulit menjadi lebih sehat dan tidak rentan mengalami breakouts. Berkat kandungan Watermelon yang menghidrasi secara optimal, Aloe Vera Juice yang menenangkan dan meregenerasi kulit, serta Niacinamide yang mencerahkan dan memudarkan bekas jerawat, toner ini menjadi solusi sempurna bagi kulit yang kering, sensitif, atau bermasalah. Selain itu, Centella Asiatica bekerja meredakan kemerahan dan memberikan perlindungan antioksidan, sementara Sodium Hyaluronate membantu menjaga kelembapan kulit lebih lama. Cocok untuk semua jenis kulit, termasuk kulit sensitif, toner ini dapat digunakan pada pagi dan malam hari setelah mencuci muka. Hydrating toner ini akan membuat kulit terasa lebih lembut, kenyal, dan bercahaya sepanjang hari.",
    ],
];
?>
